### ISSUE TITLE
Comments on Final

### ISSUE THREAD

**Issue by joseph-hellerstein** [nixiwang/PISA-and-World-Bank-Educational-Data-Project#9]
Much looks good. Some things to look at:
1. You have some code that's well documented, and other cases where the comments do not match the code (e.g., data_cleaning.py / data_cleaning). You need to clean this up.
2. named constants should be in capital letters (e.g., mapdata.py)
3. The tests you have look reasonable, but there are a lot of missing tests.

**Comment by nixiwang** [comment]
Hi Jo:
Thanks so much for your feedback! Here's the current status on each:
1. fixed and cleaned up codes.
2. will fix later.
3. Will add as much as possible. However, note there are many modules for visualization and data file management purposes only and we skipped those for testing.
